djangocalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views  # for password reset and change

from django.conf import settings
from django.conf.urls.static import static

from my_calendar.views import (
    home_view,
    calendar_view,
    all_events_view,
    event_detail,
    add_event,
    update_event,
    delete_event,
    search_pictograms,
    pictogram_detail,
    patients_list,
    add_patient,
    update_patient,
    delete_patient,
    calendar_to_pdf,
    show_information,
)

from accounts.views import (
    login_user,
    logout_user,
    register_user,
    user_detail,
    update_user,
    activate_account,
    send_activation_mail,
    user_data_privacy
)

urlpatterns = [
                path('admin/', admin.site.urls),
                path('', login_user, name="home"),
                path('calendar/<int:id_patient>/', calendar_view, name="calendar"),
                path('calendar/<int:id_patient>/<int:month>/<int:year>/', calendar_view, name="calendar"),
                path('calendar/event_detail/<int:event_id>/', event_detail, name="event-detail"),
                path('calendar/events/<int:id_patient>/', all_events_view, name="events-list"),
                path('calendar/add_event/<int:day>/<int:month>/<int:year>/', add_event, name="add-event"),
                path('calendar/add_event/', add_event, name="add-event"),
                path('calendar/update_event/<int:event_id>/', update_event, name="update-event"),
                path('calendar/delete_event/<int:event_id>/', delete_event, name="delete-event"),
                path('calendar/search_pictograms/', search_pictograms, name="search-pictograms"),
                path('calendar/pictogram/<int:picto_id>/', pictogram_detail, name="pictogram-detail"),
                path('calendar/patients/', patients_list, name="patients-list"),
                path('calendar/add_patient/', add_patient, name="add-patient"),
                path('calendar/update_patient/<int:id_patient>/', update_patient, name="update-patient"),
                path('calendar/delete_patient/<int:id_patient>/', delete_patient, name="delete-patient"),
                path('calendar/to_pdf/<int:id_patient>/<int:month>/<int:year>/', calendar_to_pdf,
                   name="calendar-to-pdf"),
                path('calendar/information/', show_information, name="show-information"),

                # Account URLs
                path('/accounts/', include('django.contrib.auth.urls')),
                path('accounts/login/', login_user, name="login"),
                path('accounts/logout/', logout_user, name="logout"),
                path('accounts/register_user/', register_user, name="register_user"),
                path('accounts/user_detail/<int:user_id>/', user_detail, name="user-detail"),
                path('accounts/update_user/<int:user_id>/', update_user, name="update-user"),
                path('accounts/user_privacy/', user_data_privacy, name="user-privacy"),

                # Password reset URLs
                path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                  template_name='password_reset/password_change_done.html'),
                   name='password_change_done'),

                path('accounts/password_change/',
                   auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
                   name='password_change'),

                path('accounts/password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
                  template_name='password_reset/password_reset_done.html'),
                   name='password_reset_done'),

                path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                    template_name='password_reset/password_reset_confirm.html'),
                   name='password_reset_confirm'),

                path('password_reset/', auth_views.PasswordResetView.as_view(
                    template_name='password_reset/password_reset_form.html'),
                     name='password_reset'),

                path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(
                  template_name='password_reset/password_reset_complete.html'),
                   name='password_reset_complete'),

                path('accounts/activate_account/<uidb64>/<token>/', activate_account, name='activate-account'),
                path('accounts/send_activation_mail/<int:user_id>/', send_activation_mail, name='send-activation-mail')


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

User._meta.get_field('email').blank = False


class Therapist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    institution = models.CharField(max_length=30, blank=True)


# Methods executed when the signal of user create or update are triggered.
@receiver(post_save, sender=User)
def create_user_therapist(sender, instance, created, **kwargs):
    if created:
        Therapist.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_therapist(sender, instance, **kwargs):
    instance.therapist.save()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Therapist


class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'required': 'True'}))
    # first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Nombre')
    # last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Apellido')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    # Override built-in style for the inputs
    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']


class TherapistForm(forms.ModelForm):
    class Meta:
        model = Therapist
        fields = ['institution', ]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.utils.safestring import mark_safe

from .forms import RegisterUserForm, UserForm, TherapistForm
# Create your views here.
from .token import account_activation_token


def login_user(request):
    """
    Login user that has been signed up before.
    :param request:
    :return: returns list of calendars if the user is logged in or the login page otherwise.
    """

    if request.user.is_authenticated:
        return redirect('patients-list')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.POST.get('next', None)
            if next_url is not None:
                return redirect(next_url)
            else:
                return redirect('patients-list')
        else:
            try:
                # Verify if the user exists but its account is not active.
                user_temp = User.objects.get(username=username)
            except:
                messages.error(request,
                               'ERROR: Nombre de usuario o contraseña incorrectas. Vuelva a intentarlo.')
            else:
                if user_temp.is_active:
                    messages.error(request,
                                   'ERROR: Nombre de usuario o contraseña incorrectas. Vuelva a intentarlo.')
                else:
                    message = f'ERROR: Su cuenta no ha sido activdada. Por favor, revise su correo y actívela.' \
                              f'<a href="{redirect("send-activation-mail", user_temp.id).url}"' \
                              f'> Volver a enviar correo</a>'

                    messages.error(request, mark_safe(message))

            return redirect('login')
    else:
        next_url = request.GET.get('next', None)
        context = {'next': next_url}
        return render(request, 'authentication/login.html', context)


def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('login')


def register_user(request):
    if request.method == 'POST':
        form_user = RegisterUserForm(request.POST)
        form_therapist = TherapistForm(request.POST)

        if form_user.is_valid() and form_therapist.is_valid():
            # Save user info and verify is is not active until email conrfirmation.
            user = form_user.save()
            user.is_active = False
            user.save()

            # Save the therapist extra info associated to the user.
            print(form_therapist.cleaned_data)
            user.therapist.institution = form_therapist.cleaned_data.get('institution')
            user.save()

            # Send activation email.
            # current_site = get_current_site(request)
            # mail_subject = 'Active su cuenta en PictoCal.'
            # message = render_to_string('authentication/activate_account_email.html', {
            #     'user': user,
            #     'domain': current_site.domain,
            #     'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            #     'token': account_activation_token.make_token(user),
            # })
            # to_email = form_user.cleaned_data.get('email')
            # email = EmailMessage(
            #     mail_subject, message, to=[to_email]
            # )
            # email.send()
            return redirect('send-activation-mail', user.id)
    else:
        form_user = RegisterUserForm()
        form_therapist = TherapistForm()

    context = {
        'form_user': form_user,
        'form_therapist': form_therapist
    }

    return render(request, 'authentication/register_user.html', context)


def user_detail(request, user_id):
    user = User.objects.get(id=user_id)
    context = {
        'user': user
    }

    return render(request, 'user_data/user_detail.html', context)


def update_user(request, user_id):
    user = User.objects.get(id=user_id)

    if request.method == "POST":
        if user is not None:
            form_user = UserForm(request.POST, instance=user)
            form_therapist = TherapistForm(request.POST, instance=user.therapist)
        if form_user.is_valid() and form_therapist.is_valid():
            form_user.save()
            form_therapist.save()
            return redirect('user-detail', user.id)

    else:
        form_user = UserForm(instance=user)
        form_therapist = TherapistForm(instance=user.therapist)

    context = {
        'form_user': form_user,
        'form_therapist': form_therapist
    }
    return render(request, 'user_data/update_user.html', context)


def activate_account(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)
        messages.success(request, "EXITO! Su cuenta ha sido activada.")

    else:
        messages.error(request, "ERROR! El enlace de activación no es válido.")

    return redirect('login')


def send_activation_mail(request, user_id):
    """
    Sends the account activation email.
    """
    user = User.objects.get(id=user_id)
    to_email = user.email
    current_site = get_current_site(request)
    mail_subject = 'Active su cuenta en PictoCal.'
    message = render_to_string('authentication/activate_account_email.html', {
        'user': user,
        'domain': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
    })
    email = EmailMessage(
        mail_subject, message, to=[to_email]
    )
    try:
        email.send()
    except:
        messages.ERROR(request, 'ERROR: Se ha producido un error. Vuelva a intentarlo')
    else:
        messages.success(request, 'EXITO: Se ha enviado un correo para que active su cuenta.')
    return redirect('login')


def user_data_privacy(request):
    return render(request, 'authentication/data_privacy.html', {})

accounts/templates/authentication/activate_account_email.html
{% autoescape off %}
Hola {{ user.username }},
Por favor, haga click sobre el enlace para activar su cuenta en PictoCal:
http://{{ domain }}{% url 'activate-account' uidb64=uid token=token %}

Atentamente,

El equipo de PictoCal
{% endautoescape %}

accounts/templates/authentication/data_privacy.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center">
    <div class="shadow-none p-3 mb-5 bg-white rounded col-md-8">
        <h1 class="text-center mb-4"> Política de privacidad </h1>
        <div class="container">
            <div class="mb-4">
                <h4 class="mb-2"> Información básica sobre Protección de Datos </h4>
                <p>
                    Para cumplir con lo estipulado en el RGPD en la normativa puesta en vigor el 25 de mayo de 2018, le informamos de que su correo electrónico quedará registrado.
                    Se utilizará únicamente para el envío del correo de autenticación y recuperación de contraseña.
                </p>
            </div>
            <div class="mb-4">
                <h4 class="mb-2"> Información sobre Cookies </h4>
                <div class="mb-3">
                    <h5>¿Qué son las cookies?</h5>
                    <p>
                        Una cookie es un fichero de pequeño tamaño que los sitios web envían al navegador y se descargan en su ordenador.
                        Las cookies permiten que la página web almacene y recupere la información sobre su visita, como su idioma preferido y otras opciones,
                        con el fin de mejorar los servicios que se ofrecen y contribuir a tener una mejor experiencia de navegación para el usuario.
                    </p>
                </div>
                <div class="mb-3">
                    <h5>Nuestras cookies</h5>
                    <p>
                        En nuestra aplicación web solo empleamos coockies técnicas, las cuales son empledas para que el usuario pueda disfrutar de servicios como la comunicación segura de datos
                        o la identificación de la sesión.
                    </p>
                </div>
                <div class="mb-3">
                    <h5>¿Cómo modificar o eliminar las cookies?</h5>
                    <p>
                        Usted puede restringir, bloquear o borrar las cookies de PictoCal o cualquier otra página web utilizando su navegador.
                        En cada navegador la operativa es diferente, puede encontrar cómo hacerlo en el menú de ayuda de su navegador dónde se establece el procedimiento para su eliminación.
                        Para más información:
                        <ul>
                            <li><a href="https://support.google.com/chrome/answer/95647?co=GENIE.Platform%25253DDesktop&hl=es">Google Chrome</a></li>
                            <li><a href="https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-sit ios-web-rastrear-preferencias">Mozilla Firefox</a></li>
                            <li><a href="https://support.apple.com/es-es/guide/safari/sfri11471/mac">Safari</a></li>
                            <li><a href="https://support.microsoft.com/es-es/help/278835/how-to-delete-cookie-f iles-in-internet-explorer">Internet Explorer</a></li>
                            <li><a href="https://privacy.microsoft.com/es-es/windows-10-microsoft-edge-and-privacy">Microsoft Edge</a></li>
                         </ul>

                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/authentication/login.html
{% extends "base.html" %}

{% block content %}
<div class="row text-center justify-content-center">
    <div class="col-md-6 bg-white p-3 rounded">
        <h1 class="mb-4"> Log in </h1>
        <form method="post" action="">
            {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label">Nombre de usuario</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Contraseña</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>

            <button type="submit" class="btn btn-outline-primary">Entrar</button>
            {% if next is not None %}
                <input type="hidden" name="next" value="{{next}}" />
            {% endif %}
        </form>
        <div class="mt-4">
            <a href="{% url 'password_reset' %}">¿Olvidó su contraseña?</a>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/authentication/register_user.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center">
    <div class="shadow-none p-3 mb-5 bg-white rounded col-md-6">
        <h1 class="text-center mb-4"> Registro </h1>
        {% for field in form_user %}
            {% for error in field.errors %}
                <p style="color: red"><i class="bi bi-exclamation-circle"></i> {{ error }}</p>
            {% endfor %}
        {% endfor %}
        {% for field in form_therapist %}
            {% for error in field.errors %}
                <p style="color: red"><i class="bi bi-exclamation-circle"></i> {{ error }}</p>
            {% endfor %}
        {% endfor %}

<!--        <form method="post" action=".">-->
<!--            {% csrf_token %}-->
<!--            {{ form_user.as_p }}-->
<!--            {{ form_therapist.as_p }}-->
<!--            <button type="submit" class="btn btn-outline-primary">Registrarse</button>-->
<!--        </form>-->
        <form action="." method="post">
            {% csrf_token %}
            <div class="mb-3">
                <input type="text" name="username" placeholder="Nombre de usuario*" value="" maxlength="150" autofocus="" class="form-control" required="" id="id_username" aria-describedby="usernameHelp">
                <div id="usernameHelp" class="form-text">*Obligatorio. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_</div>
            </div>
            <div class="mb-3">
                <input type="email" name="email" placeholder="Email*" value="" class="form-control" required="" id="id_email" aria-describedby="emailHelp">
                <div id="emailHelp" class="form-text">*Obligatorio</div>
            </div>
            <div class="mb-3">
                <input type="password" name="password1" autocomplete="new-password" class="form-control" required="" id="id_password1" aria-autocomplete="list" placeholder="Contraseña*" aria-describedby="passwordHelp">
                <div id="passwordHelp" class="form-text">*Obligatorio. Mínimo 8 caracteres.</div>
            </div>
            <div class="mb-3">
                <input type="password" name="password2" autocomplete="new-password" class="form-control" required="" id="id_password2" placeholder="Repita Contraseña*" aria-describedby="2passHelp">
                <div id="2passHelp" class="form-text">*Obligatorio. Repita su contraseña para validarla.</div>
            </div>
            <div class="mb-3">
                <input type="text" name="institution" maxlength="30" id="id_institution" placeholder="Institucion" aria-describedby="institutionHelp" class="form-control">
            </div>
            <div class="mb-3">
                <input type="checkbox" class="form-check-input" id="privacy" name="privacy" required>
                <label class="form-check-label" for="privacy">
                    <a href="{% url 'user-privacy' %}"> Doy mi consentimiento explícito para que se registren mis datos </a>
                </label>
            </div>
            <button type="submit" class="btn btn-outline-primary">Registrarse</button>
        </form>
    </div>
</div>
{% endblock content %}