djangocalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views  # for password reset and change

from django.conf import settings
from django.conf.urls.static import static

from my_calendar.views import (
    home_view,
    calendar_view,
    all_events_view,
    event_detail,
    add_event,
    update_event,
    delete_event,
    search_pictograms,
    pictogram_detail,
    patients_list,
    add_patient,
    update_patient,
    delete_patient,
    calendar_to_pdf,
    show_information,
)

from accounts.views import (
    login_user,
    logout_user,
    register_user,
    user_detail,
    update_user,
    activate_account,
    send_activation_mail,
    user_data_privacy
)

urlpatterns = [
                path('admin/', admin.site.urls),
                path('', login_user, name="home"),
                path('calendar/<int:id_patient>/', calendar_view, name="calendar"),
                path('calendar/<int:id_patient>/<int:month>/<int:year>/', calendar_view, name="calendar"),
                path('calendar/event_detail/<int:event_id>/', event_detail, name="event-detail"),
                path('calendar/events/<int:id_patient>/', all_events_view, name="events-list"),
                path('calendar/add_event/<int:day>/<int:month>/<int:year>/', add_event, name="add-event"),
                path('calendar/add_event/', add_event, name="add-event"),
                path('calendar/update_event/<int:event_id>/', update_event, name="update-event"),
                path('calendar/delete_event/<int:event_id>/', delete_event, name="delete-event"),
                path('calendar/search_pictograms/', search_pictograms, name="search-pictograms"),
                path('calendar/pictogram/<int:picto_id>/', pictogram_detail, name="pictogram-detail"),
                path('calendar/patients/', patients_list, name="patients-list"),
                path('calendar/add_patient/', add_patient, name="add-patient"),
                path('calendar/update_patient/<int:id_patient>/', update_patient, name="update-patient"),
                path('calendar/delete_patient/<int:id_patient>/', delete_patient, name="delete-patient"),
                path('calendar/to_pdf/<int:id_patient>/<int:month>/<int:year>/', calendar_to_pdf,
                   name="calendar-to-pdf"),
                path('calendar/information/', show_information, name="show-information"),

                # Account URLs
                path('/accounts/', include('django.contrib.auth.urls')),
                path('accounts/login/', login_user, name="login"),
                path('accounts/logout/', logout_user, name="logout"),
                path('accounts/register_user/', register_user, name="register_user"),
                path('accounts/user_detail/<int:user_id>/', user_detail, name="user-detail"),
                path('accounts/update_user/<int:user_id>/', update_user, name="update-user"),
                path('accounts/user_privacy/', user_data_privacy, name="user-privacy"),

                # Password reset URLs
                path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                  template_name='password_reset/password_change_done.html'),
                   name='password_change_done'),

                path('accounts/password_change/',
                   auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
                   name='password_change'),

                path('accounts/password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
                  template_name='password_reset/password_reset_done.html'),
                   name='password_reset_done'),

                path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                    template_name='password_reset/password_reset_confirm.html'),
                   name='password_reset_confirm'),

                path('password_reset/', auth_views.PasswordResetView.as_view(
                    template_name='password_reset/password_reset_form.html'),
                     name='password_reset'),

                path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(
                  template_name='password_reset/password_reset_complete.html'),
                   name='password_reset_complete'),

                path('accounts/activate_account/<uidb64>/<token>/', activate_account, name='activate-account'),
                path('accounts/send_activation_mail/<int:user_id>/', send_activation_mail, name='send-activation-mail')


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_calendar/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime


# Create your models here.
class PatientCalendar(models.Model):

    name = models.CharField(max_length=50, blank=False, null=False, default="Nombre Calendario")
    template_style = models.PositiveSmallIntegerField(blank=False, null=False, default=1)  # 1: white, 2: gray,
    # 3: yellow, 4: blue, 5: green

    # Text style
    font_style = models.CharField(max_length=20, blank=False, null=False, default='Arial,sans-serif')
    font_color = models.CharField(max_length=7, blank=False, null=False, default='#000000')
    link_color = models.CharField(max_length=7, blank=False, null=False, default='#000000')
    font_size = models.PositiveSmallIntegerField(blank=False, null=False, default=12)
    text_position_event = models.PositiveSmallIntegerField(blank=False, null=False, default=1)  # 1: above, 2: below

    month_box = models.BooleanField(default = True)
    season_box = models.BooleanField(default = True)
    extra_box = models.BooleanField(default = False)
    header_extra_box = models.CharField(max_length=50, blank=True, default='')

    therapist = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        unique_together = ('name', 'therapist',)  # a therapist cannot repeat the calendar name

    def __str__(self):
        return self.name  # just to see the title in admin area


class Event(models.Model):
    title = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    date = models.DateField()
    image = models.ImageField(blank=True, null=True, upload_to='images/')
    url_image = models.URLField(blank=True, null=True)
    type = models.PositiveSmallIntegerField(blank=False, null=False, default=1)  # 1:day event, 2:month, 3:season,
    # 4:weather, 5:extra
    patient_calendar = models.ForeignKey(PatientCalendar, blank=False, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return self.title  # just to see the title in admin area

my_calendar/views.py
from datetime import datetime
from email import header
import locale
import os
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages


from django.core.files.storage import FileSystemStorage
from django.template.loader import render_to_string
from weasyprint import HTML

import requests
from requests.auth import HTTPBasicAuth

from decouple import config

from .models import Event, PatientCalendar
from .utils import Calendar
from .forms import EventForm, PatientForm

# Create your views here.


def home_view(request):
    return render(request, "my_calendar/index.html", {"message": "hello fran"})


@login_required
def calendar_view(request, id_patient, month=datetime.now().month, year=datetime.now().year):
    """
    Shows the HTML calendar for a selected month and a selected year. The full month is shown.
    :param id_patient: id of the patient we want to show the calendar
    :param request:
    :param month: month we want to show on the calendar
    :param year: year of the month we want to show
    :return: html calendar of the month and year with the events of each day.
    """
    if request.method == 'POST':
        query = request.POST['month'].split("-")
        if len(query) == 2:
            year = int(query[0])
            month = int(query[1])

    cal = Calendar(year, month)
    # Call the formatmonth method, which returns our calendar as a table
    html_cal = cal.formatmonth(id_patient, withyear=True)

    # Retrieve the month, season and weather images
    month_event = Event.objects.filter(patient_calendar=id_patient, date__month=month, date__year=year, type=2)
    season_event = Event.objects.filter(patient_calendar=id_patient, date__month=month, date__year=year, type=3)
    weather_event = Event.objects.filter(patient_calendar=id_patient, date__month=month, date__year=year, type=4)
    extra_event = Event.objects.filter(patient_calendar=id_patient, date__month=month, date__year=year, type=5)

    context = {
        "calendar": mark_safe(html_cal),
        'id_patient': id_patient,
        'month': str(month).zfill(2),  # fill with leading 0 to use it in the input value form control.
        'year': year,
        'month_event': month_event,
        'season_event': season_event,
        'weather_event': weather_event,
        'extra_event': extra_event,
        'patient_calendar': PatientCalendar.objects.get(id=id_patient)
    }
    print(context['season_event'])
    return render(request, "my_calendar/calendar.html", context)


@login_required
def all_events_view(request, id_patient):
    events_list = Event.objects.filter(patient_calendar=id_patient)
    context = {
        'events_list': events_list,
        'id_patient': id_patient
    }
    return render(request, 'my_calendar/events_list.html', context)


@login_required
def event_detail(request, event_id=None):
    context = {}
    if event_id is not None:
        event = Event.objects.get(id=event_id)
        context['event'] = event

    return render(request, "my_calendar/event_detail.html", context)


@login_required
def add_event(request, day=datetime.now().day, month=datetime.now().month, year=datetime.now().year):
    context = {
        'day': str(day).zfill(2),
        'month': str(month).zfill(2),
        'year': year,
    }

    event_date = f'{year}-{str(month).zfill(2)}-{str(day).zfill(2)}'

    picto = request.GET.get('picto', 'None')
    if picto is not None:
        context['picto_id'] = picto

    initial_values = {
        'date': event_date
    }

    # Init the form with the given patient.
    id_patient = request.GET.get('id_patient', None)
    if id_patient is not None:
        initial_values['patient_calendar'] = id_patient

    # Init the form with the given type of event.
    event_type = request.GET.get('type', None)
    if event_type is not None:
        initial_values['type'] = event_type
    else:
        initial_values['type'] = '1'

    context['id_patient'] = id_patient
    context['type'] = event_type

    if request.method == "POST":
        # Si no es tipo evento, debemos añadir el dia 01 al mes para que lo admita la BD.
        if request.POST.get('type') != '1':
            post = request.POST.copy()
            post['date'] = f'{post["date"]}-01'
            request.POST = post

        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            new_event = form.save()
            messages.success(request, 'EXITO! El evento se ha creado correctamente.')
            return redirect('event-detail', event_id=new_event.id)

        context['previous_page'] = request.POST.get('back')  # obtain previous web page.
    else:
        form = EventForm(initial=initial_values)
        context['previous_page'] = request.META.get('HTTP_REFERER')  # obtain previous web page.

    context['form'] = form

    return render(request, 'my_calendar/add_eventV2.html', context)


@login_required
def update_event(request, event_id):
    context = {}
    event = Event.objects.get(id=event_id)
    context['event'] = event

    if request.method == "POST":
        # Si no es tipo evento, debemos añadir el dia 01 al mes para que lo admita la BD.
        if request.POST.get('type') != '1':
            post = request.POST.copy()
            post['date'] = f'{post["date"]}-01'
            request.POST = post

        if event.image:
            image_path = event.image.path

        form = EventForm(request.POST, request.FILES, instance=event)

        if form.is_valid():
            print(request.POST.get('image-clear'))
            if request.POST.get('image-clear') == 'on':
                if os.path.exists(image_path):
                    os.remove(image_path)
            form.save()
            print('Guardado')
            return redirect('event-detail', event_id=event_id)
        else:
            print('Not valid')
    else:
        form = EventForm(instance=event)

    context['form'] = form
    print(form.non_field_errors)

    return render(request, 'my_calendar/update_eventV2.html', context)


@login_required
def delete_event(request, event_id):
    context = {}
    event = Event.objects.get(id=event_id)
    id_patient = event.patient_calendar.id
    month = event.date.month
    year = event.date.year
    if event.image and os.path.exists(event.image.path):
        os.remove(event.image.path)
    event.delete()
    messages.success(request, 'EXITO! EL evento se ha eliminao correctamente.')
    return redirect('calendar', id_patient, month, year)


def search_pictograms(request):
    context = {}

    if request.method == 'POST':
        searched = request.POST['searched']
        context['searched'] = searched

        # Query data to the API
        language = 'es'
        url = f'https://api.arasaac.org/api/pictograms/{language}/search/{searched}'
        api_user = config('API_USER')
        api_pass = config('API_PASS')
        response = requests.get(url, auth=HTTPBasicAuth(api_user, api_pass))

        if response.status_code == 200:
            result = response.json()
            context['result'] = result
            context['success'] = True
        else:
            context['success'] = False
            context['msg'] = 'ERROR, try again.'

    return render(request, 'my_calendar/search_pictograms.html', context)


def pictogram_detail(request, picto_id):
    context = {}

    # Query data to the API
    language = 'es'
    url = f'https://api.arasaac.org/api/pictograms/es/{picto_id}'
    user = config("API_USER")
    password = config("API_PASS")
    response = requests.get(url, auth=HTTPBasicAuth(user, password))

    if response.status_code == 200:
        context['result'] = response.json()
        context['success'] = True
    else:
        context['success'] = False
        context['msg'] = 'ERROR, try again.'
    return render(request, 'my_calendar/pictogram_detail.html', context)


@login_required
def patients_list(request):
    patients = PatientCalendar.objects.filter(therapist_id=request.user.id)
    context = {
        'patients_list': patients
    }
    return render(request, 'my_calendar/patients_list.html', context)


@login_required
def add_patient(request):

    if request.method == "POST":
        form = PatientForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "EXITO! El calendario se ha creado correctamente.")
            return redirect('patients-list')
        else:
            print(form.errors.as_data())
    else:
        form = PatientForm(initial={'therapist': request.user.id})

    context = {
        'form': form,
    }
    return render(request, 'my_calendar/add_patient.html', context)


@login_required
def update_patient(request, id_patient):
    """
    Actualizar datos del calendario enviado por id_patient
    :param request:
    :param id_patient: id del calendario a actualizar
    :return: si los datos son validos se redirecciona al calendario. Si la peticion es GET se renderiza el
    formulario para actualizar los datos.
    """

    context = {}
    patient = PatientCalendar.objects.get(id=id_patient)

    if request.method == 'POST':
        form = PatientForm(request.POST, instance=patient)

        if form.is_valid():
            form.save()
            messages.success(request, "EXITO! El calendario ha sido actualizado!")
            return redirect('calendar', id_patient)
        else:
            print(form.errors)
    else:
        form = PatientForm(instance=patient)

    context['form'] = form
    context['patient'] = patient

    return render(request, 'my_calendar/update_patient.html', context)


@login_required
def delete_patient(request, id_patient):
    """
    Eliminar un calendario.
    :param request:
    :param id_patient: id del calendario del paciente a eliminar

my_calendar/templates/my_calendar/add_event.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6 rounded bg-white p-3">
        <h1 class="text-center mb-3">
        {% if type == '1' %}
             Nuevo Evento
        {% elif type == '2' %}
            Nuevo Mes
        {% elif type == '3' %}
            Nueva Estación
        {% elif type == '4' %}
            Nuevo Tiempo
        {% endif %}
        </h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit" value="Crear" class="btn btn-outline-primary">
        </form>
    </div>
</div>
{% endblock content %}

my_calendar/templates/my_calendar/event_detail.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-4 rounded bg-white p-3">
        <div class="card">
            <div class="card-header">
                <h2> {{event.title}} </h2>
            </div>
            <div class="card-body">
                {% if event.type == 1 %}
                    <h4> {{ event.date|date:"d \d\e F \d\e Y" }} </h4>
                {% else %}
                    <h4> {{ event.date|date:"F \d\e Y" }} </h4>
                {% endif %}

                <p> {{ event.description }} </p>
                {% if event.url_image %}
                    <img src="{{event.url_image }}" width="200px" height="200px">
                {% elif event.image %}
                    <img src="{{event.image.url }}" width="200px" height="200px">
                {% endif %}

            </div>
            <div class="card-footer">
                <a href="{% url 'calendar' event.patient_calendar.id event.date.month event.date.year %}" class="btn btn-outline-success btn-sm">Ver en calendario</a>
                <a href="{% url 'update-event' event.id %}" class="btn btn-sm btn-outline-secondary">Modificar</a>
                <a class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal">Eliminar</a>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">¿Estás seguro?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ¿Éstas seguro de que deseas eliminar el evento <strong> {{ event.title }}</strong> con fecha el {{ event.date|date:"d \d\e F \d\e Y" }} ?
      </div>
      <div class="modal-footer">
        <a type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</a>
        <a type="button" class="btn btn-danger" href="{% url 'delete-event' event.id %}">Eliminar</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

my_calendar/templates/my_calendar/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{message}}</title>
    <h1>Hello {{ message }}</h1>
</head>
<body>

</body>
</html>

my_calendar/templates/my_calendar/update_patient.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6 rounded bg-white p-3">
        <h1 class="text-center mb-3"> Editar Calendario </h1>

        {% for field in form %}
        {% for error in field.errors %}
        <p style="color: red"><i class="bi bi-exclamation-circle"></i> {{ error }}</p>
        {% endfor %}
        {% endfor %}

        <form action="." method="post">
            {% csrf_token %}
            <input type="text" name="name" class="form-control my-3" placeholder="Nombre" maxlength="50" required id="id_name" value="{{ patient.name }}">
            <input type="number" name="therapist" class="form-control mb-3" placeholder="Terapeuta" id="id_therapist" hidden required value="{{user.id}}">

            <div class="accordion accordion-flush my-4" id="accordionFlushExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                            Estilo del calendario
                        </button>
                    </h2>
                    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="template_style" id="inlineRadio1" value="1"
                                       {% if patient.template_style == 1 %}
                                       checked
                                       {%endif %}
                                >
                                <label class="form-check-label" for="inlineRadio1">Fondo blanco</label>
                            </div>
                            <div class="form-check form-check-inline mb-3">
                                <input class="form-check-input" type="radio" name="template_style" id="inlineRadio2" value="2"
                                       {% if patient.template_style == 2 %}
                                       checked
                                       {%endif %}
                                >
                                <label class="form-check-label" for="inlineRadio2">Fondo gris</label>
                            </div>
                            <div class="form-check form-check-inline mb-3">
                                <input class="form-check-input" type="radio" name="template_style" id="inlineRadio3" value="3"
                                       {% if patient.template_style == 3 %}
                                       checked
                                       {%endif %}
                                >
                                <label class="form-check-label" for="inlineRadio3">Fondo amarillo</label>
                            </div>
                            <div class="form-check form-check-inline mb-3">
                                <input class="form-check-input" type="radio" name="template_style" id="inlineRadio4" value="4"
                                       {% if patient.template_style == 4 %}
                                       checked
                                       {%endif %}
                                >
                                <label class="form-check-label" for="inlineRadio4">Fondo azul</label>
                            </div>
                            <div class="form-check form-check-inline mb-3">
                                <input class="form-check-input" type="radio" name="template_style" id="inlineRadio5" value="5"
                                       {% if patient.template_style == 5 %}
                                       checked
                                       {%endif %}
                                >
                                <label class="form-check-label" for="inlineRadio4">Fondo verde</label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingTwo">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                            Estilo del texto
                        </button>
                    </h2>
                    <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body">
                            <div class="mb-3">
                                <label for="font-color" class="form-label">Color base: </label>
                                <input class="form-control form-control-color" type="color" value="{{patient.font_color}}" id="font-color" name="font_color" list="presetColors" aria-describedby="colorHelp">
                                <datalist id="presetColors">
                                    <option>#000000</option>
                                    <option>#ff0000</option>
                                    <option>#00ff00</option>
                                    <option>#0000ff</option>
                                </datalist>
                                <div id="colorHelp" class="form-text">Color de la fecha y titulos del calendario.</div>
                            </div>
                            <div class="mb-3">
                                <label for="font-color" class="form-label">Color eventos: </label>
                                <input class="form-control form-control-color" type="color" value="{{patient.link_color}}" id="link-color" name="link_color" list="presetColors" aria-describedby="linkHelp">
                                <div id="linkHelp" class="form-text">Color del nombre de los eventos.</div>
                            </div>
                            <div class="mb-3">
                                <label for="font-size" class="form-label">Tamaño del texto:</label>
                                <select class="form-select" aria-label="Tamaño del texto" id="font-size" name="font_size">
                                    <option value="12" {% if patient.font_size == 12 %} selected {%endif%}>12</option>
                                    <option value="14" {% if patient.font_size == 14 %} selected {%endif%}>14</option>
                                    <option value="16" {% if patient.font_size == 16 %} selected {%endif%}>16</option>
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="font-style" class="form-label">Tipo de letra:</label>
                                <select class="form-select" aria-label="Tipo de letra" id="font-style" name="font_style">
                                    <option value="Arial,sans-serif" {% if patient.font_style == "Arial,sans-serif"%} selected {%endif%}>
                                    Sin serifa
                                    </option>
                                    <option value="Times,serif" {% if patient.font_style == "Times,serif"%} selected {%endif%} >Con serifa</option>
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="text-position" class="form-label">Posición del nombre del evento:</label>
                                <select class="form-select" aria-label="Posición del texto" id="text-position" name="text_position_event">
                                    <option value="1" {% if patient.text_position_event == 1 %} selected {%endif%}>Encima del pictograma</option>
                                    <option value="2" {% if patient.text_position_event == 2 %} selected {%endif%}>Debajo del pictograma</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingThird">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThird" aria-expanded="false" aria-controls="flush-collapseThird">
                            Número de cajas
                        </button>
                    </h2>
                    <div id="flush-collapseThird" class="accordion-collapse collapse" aria-labelledby="flush-headingThird" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name = "month_box" id="month_box"
                                {% if patient.month_box %}
                                checked
                                {% endif %}>
                                <label class="form-check-label" for="month_box">
                                  Mes
                                </label>
                              </div>
                              <div class="form-check">
                                <input class="form-check-input" type="checkbox" name = "season_box" id="season_box"
                                {% if patient.season_box %}
                                checked
                                {% endif %}>
                                <label class="form-check-label" for="season_box">
                                  Estación
                                </label>
                              </div>
                              <div class="form-check">
                                <input class="form-check-input" type="checkbox" name = "extra_box" id="extra_box"
                                {% if patient.extra_box %}
                                checked
                                {% endif %}>
                                <label class="form-check-label" for="extra_box">
                                  Extra
                                </label>
                                {% if patient.extra_box %}
                                    <input type="text" placeholder="Nombre de la caja extra" name="header_extra_box" id="name_extra_box" class="form-control my-3 d-block" value="{{ patient.header_extra_box }}">
                                {% else %}
                                    <input type="text" placeholder="Nombre de la caja extra" name="header_extra_box" id="name_extra_box" class="form-control my-3 d-none">
                                {% endif %}
                              </div>
                            <div id="colorHelp" class="form-text">Número de cajas que tendrá la plantilla.</div>
                        </div>
                    </div>
                </div>
            </div>

            <input type="submit" name="submit" value="Aceptar" class="btn btn-outline-primary">
            <a class="btn btn-outline-danger" href="{% url 'patients-list' %}">Cancelar</a>
        </form>
    </div>
</div>
{% endblock content %}